# IPL Analytics & Strategy Platform

## Phase 2 – Data Engineering

### Notebook 01

# Dataset Discovery & Metadata Extraction

---

### Objectives

- Validate raw IPL dataset
- Discover available match files
- Extract metadata from Cricsheet info files
- Perform data quality validation
- Generate discovery artifacts

In [ ]:
from config.config import *

from src.discovery import (
    build_dataset_catalog,
    build_dataset_metadata,
    build_discovery_report
)

from src.validation.quality_checks import (
    validate_dataset
)

from src.exports import (
    export_discovery_artifacts
)

from src.utils.logging_utils import (
    configure_logger,
    get_logger
)

In [2]:
configure_logger()

logger = get_logger(__name__)

logger.info("Notebook 01 started.")

2026-07-02 22:29:49 | INFO     | __main__ | Notebook 01 started.

In [3]:
catalog_df = build_dataset_catalog(
    RAW_DATA_DIR
)

catalog_df.head()

2026-07-02 22:29:49 | INFO     | src.discovery.catalog | Starting dataset discovery...

2026-07-02 22:29:49 | INFO     | src.discovery.catalog | CSV files discovered: 2487

2026-07-02 22:29:49 | WARNING  | src.utils.file_utils | Skipping non-match CSV file: all_matches.csv (Unable to extract match ID from 'all_matches.csv'.)

2026-07-02 22:29:49 | INFO     | src.discovery.catalog | Matches discovered: 1243

2026-07-02 22:29:49 | INFO     | src.discovery.catalog | Dataset catalog successfully built.

,match_id,info_file,delivery_file,has_info,has_delivery,is_complete
0,335982,D:\IPL-Analytics-Strategy-Platform\data\raw\ip...,D:\IPL-Analytics-Strategy-Platform\data\raw\ip...,True,True,True
1,335983,D:\IPL-Analytics-Strategy-Platform\data\raw\ip...,D:\IPL-Analytics-Strategy-Platform\data\raw\ip...,True,True,True
2,335984,D:\IPL-Analytics-Strategy-Platform\data\raw\ip...,D:\IPL-Analytics-Strategy-Platform\data\raw\ip...,True,True,True
3,335985,D:\IPL-Analytics-Strategy-Platform\data\raw\ip...,D:\IPL-Analytics-Strategy-Platform\data\raw\ip...,True,True,True
4,335986,D:\IPL-Analytics-Strategy-Platform\data\raw\ip...,D:\IPL-Analytics-Strategy-Platform\data\raw\ip...,True,True,True

In [4]:
metadata_df = build_dataset_metadata(
    catalog_df
)

metadata_df.head()

2026-07-02 22:29:49 | INFO     | src.discovery.metadata | Starting metadata extraction...

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335982_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335983_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335984_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335985_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335986_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335987_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335988_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335989_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335990_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335991_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335992_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335993_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335994_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335995_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335996_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335997_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335998_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 335999_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 336000_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 336001_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 336002_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 336003_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 336004_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 336005_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 336006_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 336007_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 336008_info.csv

2026-07-02 22:29:49 | INFO     | src.discovery.parser | Parsing 336009_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336010_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336011_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336012_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336013_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336014_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336015_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336016_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336017_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336018_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336019_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336020_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336021_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336022_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336023_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336024_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336025_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336026_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336027_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336028_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336029_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336031_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336032_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336033_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336034_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336035_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336036_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336037_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336038_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336039_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 336040_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392181_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392182_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392183_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392184_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392185_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392186_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392188_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392189_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392190_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392191_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392192_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392194_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392195_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392196_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392197_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392198_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392199_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392200_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392201_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392202_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392203_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392204_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392205_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392206_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392207_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392208_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392209_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392210_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392211_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392212_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392213_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392214_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392215_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392216_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392217_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392218_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392219_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392220_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392221_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392222_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392223_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392224_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392225_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392226_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392227_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392228_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392229_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392230_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392231_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392232_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392233_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392234_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392235_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392236_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392237_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392238_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 392239_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419106_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419107_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419108_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419109_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419110_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419111_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419112_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419113_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419114_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419115_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419116_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419117_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419118_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419119_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419120_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419121_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419122_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419123_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419124_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419125_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419126_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419127_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419128_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419129_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419130_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419131_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419132_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419133_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419134_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419135_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419136_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419137_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419138_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419139_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419140_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419141_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419142_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419143_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419144_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419145_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419146_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419147_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419148_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419149_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419150_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419151_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419152_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419153_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419154_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419155_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419156_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419157_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419158_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419159_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419160_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419161_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419162_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419163_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419164_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 419165_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 501198_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 501199_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 501200_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 501201_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 501202_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 501203_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 501204_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 501205_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 501206_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 501207_info.csv

2026-07-02 22:29:50 | INFO     | src.discovery.parser | Parsing 501208_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501209_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501210_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501211_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501212_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501213_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501214_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501215_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501216_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501218_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501219_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501220_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501221_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501222_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501223_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501224_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501225_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501226_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501227_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501228_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501229_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501230_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501231_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501232_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501233_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501234_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501235_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501236_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501237_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501238_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501239_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501240_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501241_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501242_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501243_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501244_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501245_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501246_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501247_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501248_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501249_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501250_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501251_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501252_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501253_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501254_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501255_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501256_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501257_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501258_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501259_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501260_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501261_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501262_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501263_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501264_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501265_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501266_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501267_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501268_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501269_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501270_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 501271_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548306_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548307_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548308_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548309_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548310_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548311_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548312_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548313_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548314_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548315_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548316_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548317_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548318_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548319_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548320_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548321_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548322_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548323_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548324_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548325_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548326_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548327_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548328_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548329_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548330_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548331_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548332_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548333_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548334_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548335_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548336_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548337_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548339_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548341_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548342_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548343_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548344_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548345_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548346_info.csv

2026-07-02 22:29:51 | INFO     | src.discovery.parser | Parsing 548347_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548348_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548349_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548350_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548351_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548352_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548353_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548354_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548355_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548356_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548357_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548358_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548359_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548360_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548361_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548362_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548363_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548364_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548365_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548366_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548367_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548368_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548369_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548370_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548371_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548372_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548373_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548374_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548375_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548376_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548377_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548378_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548379_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548380_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 548381_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 597998_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 597999_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598000_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598001_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598002_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598003_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598004_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598005_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598006_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598007_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598008_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598009_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598010_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598011_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598012_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598013_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598014_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598015_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598016_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598017_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598018_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598019_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598020_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598021_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598022_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598023_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598024_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598025_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598026_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598027_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598028_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598029_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598030_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598031_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598032_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598033_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598034_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598035_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598036_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598037_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598038_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598039_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598040_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598041_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598042_info.csv

2026-07-02 22:29:52 | INFO     | src.discovery.parser | Parsing 598043_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598044_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598045_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598046_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598047_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598048_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598049_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598050_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598051_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598052_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598053_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598054_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598055_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598056_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598057_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598058_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598059_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598060_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598061_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598062_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598063_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598064_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598065_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598066_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598067_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598068_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598069_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598070_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598071_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598072_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 598073_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729279_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729281_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729283_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729285_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729287_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729289_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729291_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729293_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729295_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729297_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729299_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729301_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729303_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729305_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729307_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729309_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729311_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729313_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729315_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 729317_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733971_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733973_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733975_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733977_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733979_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733981_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733983_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733985_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733987_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733989_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733991_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733993_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733995_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733997_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 733999_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 734001_info.csv

2026-07-02 22:29:53 | INFO     | src.discovery.parser | Parsing 734003_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734005_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734007_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734009_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734011_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734013_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734015_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734017_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734019_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734021_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734023_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734025_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734027_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734029_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734031_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734033_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734035_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734037_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734039_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734041_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734043_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734045_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734047_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 734049_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829705_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829707_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829709_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829711_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829713_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829715_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829717_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829719_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829721_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829723_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829725_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829727_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829729_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829731_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829733_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829735_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829737_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829739_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829741_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829743_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829745_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829747_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829749_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829751_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829753_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829757_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829759_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829761_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829763_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829765_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829767_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829769_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829771_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829773_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829775_info.csv

2026-07-02 22:29:54 | INFO     | src.discovery.parser | Parsing 829777_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829779_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829781_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829783_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829785_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829787_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829789_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829791_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829793_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829795_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829797_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829799_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829801_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829803_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829805_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829807_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829809_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829811_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829813_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829815_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829817_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829819_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829821_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 829823_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980901_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980903_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980905_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980907_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980909_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980911_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980913_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980915_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980917_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980919_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980921_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980923_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980925_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980927_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980929_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980931_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980933_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980935_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980937_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980939_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980941_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980943_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980945_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980947_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980949_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980951_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980953_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980955_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980957_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980959_info.csv

2026-07-02 22:29:55 | INFO     | src.discovery.parser | Parsing 980961_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980963_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980965_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980967_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980969_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980971_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980973_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980975_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980977_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980979_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980981_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980983_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980985_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980987_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980989_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980991_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980993_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980995_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980997_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 980999_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 981001_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 981003_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 981005_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 981007_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 981009_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 981011_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 981013_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 981015_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 981017_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 981019_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082591_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082592_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082593_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082594_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082595_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082596_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082597_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082598_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082599_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082600_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082601_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082602_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082603_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082604_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082605_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082606_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082607_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082608_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082609_info.csv

2026-07-02 22:29:56 | INFO     | src.discovery.parser | Parsing 1082610_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082611_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082612_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082613_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082614_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082615_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082616_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082617_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082618_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082620_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082621_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082622_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082623_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082624_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082625_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082626_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082627_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082628_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082629_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082630_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082631_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082632_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082633_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082634_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082635_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082636_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082637_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082638_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082639_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082640_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082641_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082642_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082643_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082644_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082645_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082646_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082647_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082648_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082649_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1082650_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1136561_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1136562_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1136563_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1136564_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1136565_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1136566_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1136567_info.csv

2026-07-02 22:29:57 | INFO     | src.discovery.parser | Parsing 1136568_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136569_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136570_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136571_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136572_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136573_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136574_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136575_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136576_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136577_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136578_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136579_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136580_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136581_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136582_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136583_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136584_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136585_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136586_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136587_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136588_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136589_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136590_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136591_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136592_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136593_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136594_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136595_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136596_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136597_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136598_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136599_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136600_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136601_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136602_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136603_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136604_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136605_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136606_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136607_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136608_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136609_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136610_info.csv

2026-07-02 22:29:58 | INFO     | src.discovery.parser | Parsing 1136611_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1136612_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1136613_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1136614_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1136615_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1136616_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1136617_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1136618_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1136619_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1136620_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175356_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175357_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175358_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175359_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175360_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175361_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175362_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175363_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175364_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175365_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175366_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175367_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175368_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175369_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175370_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175371_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1175372_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1178393_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1178394_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1178395_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1178396_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1178397_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1178398_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1178399_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1178400_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1178401_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1178402_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1178403_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1178404_info.csv

2026-07-02 22:29:59 | INFO     | src.discovery.parser | Parsing 1178405_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178406_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178407_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178408_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178409_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178410_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178411_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178412_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178413_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178414_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178415_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178416_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178417_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178418_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178419_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178420_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178421_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178422_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178423_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178424_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178425_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178426_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178427_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178428_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178429_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178430_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1178431_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1181764_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1181766_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1181767_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1181768_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1216492_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1216493_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1216494_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1216495_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1216496_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1216497_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1216498_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1216499_info.csv

2026-07-02 22:30:00 | INFO     | src.discovery.parser | Parsing 1216500_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216501_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216502_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216503_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216504_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216505_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216506_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216507_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216508_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216509_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216510_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216511_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216512_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216513_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216514_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216515_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216516_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216517_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216518_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216519_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216520_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216521_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216522_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216523_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216524_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216525_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216526_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216527_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216528_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216529_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216530_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216531_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216532_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216533_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216534_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216535_info.csv

2026-07-02 22:30:01 | INFO     | src.discovery.parser | Parsing 1216536_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1216537_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1216538_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1216539_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1216540_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1216541_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1216542_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1216543_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1216544_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1216545_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1216546_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1216547_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1237177_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1237178_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1237180_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1237181_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254058_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254059_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254060_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254061_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254062_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254063_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254064_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254065_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254066_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254067_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254068_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254069_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254070_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254071_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254072_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254073_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254074_info.csv

2026-07-02 22:30:02 | INFO     | src.discovery.parser | Parsing 1254075_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254076_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254077_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254078_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254079_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254080_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254081_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254082_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254083_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254084_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254085_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254086_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254087_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254088_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254089_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254090_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254091_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254092_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254093_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254094_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254095_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254096_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254097_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254098_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254099_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254100_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254101_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254102_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254103_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254104_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254105_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254106_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254107_info.csv

2026-07-02 22:30:03 | INFO     | src.discovery.parser | Parsing 1254108_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1254109_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1254110_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1254111_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1254112_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1254113_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1254114_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1254115_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1254116_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1254117_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304047_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304048_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304049_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304050_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304051_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304052_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304053_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304054_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304055_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304056_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304057_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304058_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304059_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304060_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304061_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304062_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304063_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304064_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304065_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304066_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304067_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304068_info.csv

2026-07-02 22:30:04 | INFO     | src.discovery.parser | Parsing 1304069_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304070_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304071_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304072_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304073_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304074_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304075_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304076_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304077_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304078_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304079_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304080_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304081_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304082_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304083_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304084_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304085_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304086_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304087_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304088_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304089_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304090_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304091_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304092_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304093_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304094_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304095_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304096_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304097_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304098_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304099_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304100_info.csv

2026-07-02 22:30:05 | INFO     | src.discovery.parser | Parsing 1304101_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304102_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304103_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304104_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304105_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304106_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304107_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304108_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304109_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304110_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304111_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304112_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304113_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304114_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304115_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1304116_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1312197_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1312198_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1312199_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1312200_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1359475_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1359476_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1359477_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1359478_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1359479_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1359480_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1359481_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1359482_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1359483_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1359484_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1359485_info.csv

2026-07-02 22:30:06 | INFO     | src.discovery.parser | Parsing 1359486_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359487_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359488_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359489_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359490_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359491_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359492_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359493_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359494_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359495_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359496_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359497_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359498_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359499_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359500_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359501_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359502_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359503_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359504_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359505_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359506_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359507_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359508_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359509_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359510_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359511_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359512_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359513_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359514_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359515_info.csv

2026-07-02 22:30:07 | INFO     | src.discovery.parser | Parsing 1359516_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359517_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359518_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359519_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359520_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359521_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359522_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359523_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359524_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359525_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359526_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359527_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359528_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359529_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359530_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359531_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359532_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359533_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359534_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359535_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359536_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359537_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359538_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359539_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359540_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359541_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359542_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359543_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1359544_info.csv

2026-07-02 22:30:08 | INFO     | src.discovery.parser | Parsing 1370350_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1370351_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1370352_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1370353_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422119_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422120_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422121_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422122_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422123_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422124_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422125_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422126_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422127_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422128_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422129_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422130_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422131_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422132_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422133_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422134_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422135_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422136_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422137_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422138_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1422139_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1426260_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1426261_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1426262_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1426263_info.csv

2026-07-02 22:30:09 | INFO     | src.discovery.parser | Parsing 1426264_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426265_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426266_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426267_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426268_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426269_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426270_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426271_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426272_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426273_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426274_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426275_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426276_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426277_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426278_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426279_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426280_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426281_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426282_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426283_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426284_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426285_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426286_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426287_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426288_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426289_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426290_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426291_info.csv

2026-07-02 22:30:10 | INFO     | src.discovery.parser | Parsing 1426292_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426293_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426294_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426295_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426296_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426297_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426298_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426299_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426300_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426302_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426303_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426305_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426306_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426307_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426309_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426310_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426311_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1426312_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1473438_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1473439_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1473440_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1473441_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1473442_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1473443_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1473444_info.csv

2026-07-02 22:30:11 | INFO     | src.discovery.parser | Parsing 1473445_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473446_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473447_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473448_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473449_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473450_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473451_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473452_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473453_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473454_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473455_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473456_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473457_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473458_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473459_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473460_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473461_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473462_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473463_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473464_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473465_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473466_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473467_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473468_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473469_info.csv

2026-07-02 22:30:12 | INFO     | src.discovery.parser | Parsing 1473470_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473471_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473472_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473473_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473474_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473475_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473476_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473477_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473478_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473479_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473480_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473481_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473482_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473483_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473484_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473485_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473486_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473487_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473488_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473489_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473490_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473491_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473492_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473493_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473494_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473495_info.csv

2026-07-02 22:30:13 | INFO     | src.discovery.parser | Parsing 1473497_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473498_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473499_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473500_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473501_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473502_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473503_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473504_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473505_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473506_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473507_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473508_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473509_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473510_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1473511_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1485779_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1527674_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1527675_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1527676_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1527677_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1527678_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1527679_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1527680_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1527681_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1527682_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1527683_info.csv

2026-07-02 22:30:14 | INFO     | src.discovery.parser | Parsing 1527684_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1527685_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1527686_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1527687_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1527688_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1527689_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1527690_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1527691_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1527692_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1527693_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529264_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529265_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529266_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529267_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529268_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529269_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529270_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529271_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529272_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529273_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529274_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529275_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529276_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529277_info.csv

2026-07-02 22:30:15 | INFO     | src.discovery.parser | Parsing 1529278_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529279_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529280_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529281_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529282_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529283_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529284_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529285_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529286_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529287_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529288_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529289_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529290_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529291_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529292_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529293_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529294_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529295_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529296_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529297_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529298_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529299_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529300_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529301_info.csv

2026-07-02 22:30:16 | INFO     | src.discovery.parser | Parsing 1529302_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1529303_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1529304_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1529305_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1529306_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1529307_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1529308_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1529309_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1529310_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1529311_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1529312_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1529313_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1535462_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1535463_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1535464_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.parser | Parsing 1535465_info.csv

2026-07-02 22:30:17 | INFO     | src.discovery.metadata | Metadata extracted for 1243 matches.

,match_id,season,date,team1,team2,venue,city,winner,toss_winner,toss_decision,...,winner_runs,winner_wickets,balls_per_over,match_number,target_runs,target_overs,event_name,stage,overs,method
0,335982,2007/08,2008/04/18,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,140,None,6,1,223,20,Indian Premier League,None,20,None
1,335983,2007/08,2008/04/19,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings,Chennai Super Kings,bat,...,33,None,6,2,241,20,Indian Premier League,None,20,None
2,335984,2007/08,2008/04/19,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Delhi,Delhi Daredevils,Rajasthan Royals,bat,...,None,9,6,3,130,20,Indian Premier League,None,20,None
3,335985,2007/08,2008/04/20,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai,Royal Challengers Bangalore,Mumbai Indians,bat,...,None,5,6,5,166,20,Indian Premier League,None,20,None
4,335986,2007/08,2008/04/20,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Kolkata,Kolkata Knight Riders,Deccan Chargers,bat,...,None,5,6,4,111,20,Indian Premier League,None,20,None

In [5]:
validation_report = validate_dataset(
    catalog_df,
    metadata_df
)

validation_report

2026-07-02 22:30:17 | INFO     | src.validation.quality_checks | Running dataset validation...

2026-07-02 22:30:17 | INFO     | src.validation.quality_checks | Dataset validation completed.

{'total_matches': 1243,
 'complete_matches': 1243,
 'missing_info_files': 0,
 'missing_delivery_files': 0,
 'duplicate_match_ids': 0,
 'missing_season': 0,
 'missing_date': 0,
 'missing_team1': 0,
 'missing_team2': 0,
 'missing_venue': 0,
 'missing_city': 0,
 'missing_winner': 25,
 'earliest_season': '2007/08',
 'latest_season': '2026',
 'unique_teams': 19,
 'unique_venues': 60,
 'unique_cities': 38}

In [6]:
report_df = build_discovery_report(
    validation_report
)

report_df

2026-07-02 22:30:17 | INFO     | src.discovery.discovery_report | Building discovery report...

2026-07-02 22:30:17 | INFO     | src.discovery.discovery_report | Discovery report created.

                    Metric    Value
0            total_matches     1243
1         complete_matches     1243
2       missing_info_files        0
3   missing_delivery_files        0
4      duplicate_match_ids        0
5           missing_season        0
6             missing_date        0
7            missing_team1        0
8            missing_team2        0
9            missing_venue        0
10            missing_city        0
11          missing_winner       25
12         earliest_season  2007/08
13           latest_season     2026
14            unique_teams       19
15           unique_venues       60
16           unique_cities       38

In [7]:
export_discovery_artifacts(
    catalog_df=catalog_df,
    metadata_df=metadata_df,
    report_df=report_df,
    output_directory=STAGING_DIR
)

2026-07-02 22:30:17 | INFO     | src.exports.exporter | Exporting discovery artifacts...

2026-07-02 22:30:17 | INFO     | src.utils.io_utils | CSV saved: D:\IPL-Analytics-Strategy-Platform\data\processed\staging\dataset_catalog.csv

2026-07-02 22:30:17 | INFO     | src.utils.io_utils | CSV saved: D:\IPL-Analytics-Strategy-Platform\data\processed\staging\dataset_metadata.csv

2026-07-02 22:30:17 | INFO     | src.utils.io_utils | CSV saved: D:\IPL-Analytics-Strategy-Platform\data\processed\staging\discovery_report.csv

2026-07-02 22:30:17 | INFO     | src.exports.exporter | Discovery artifacts exported successfully.

In [8]:
print("=" * 60)

print("IPL DATASET DISCOVERY SUMMARY")

print("=" * 60)

for metric, value in validation_report.items():

    print(f"{metric:<30} : {value}")

print("=" * 60)

logger.info("Notebook 01 completed successfully.")

2026-07-02 22:30:17 | INFO     | __main__ | Notebook 01 completed successfully.

============================================================
IPL DATASET DISCOVERY SUMMARY
============================================================
total_matches                  : 1243
complete_matches               : 1243
missing_info_files             : 0
missing_delivery_files         : 0
duplicate_match_ids            : 0
missing_season                 : 0
missing_date                   : 0
missing_team1                  : 0
missing_team2                  : 0
missing_venue                  : 0
missing_city                   : 0
missing_winner                 : 25
earliest_season                : 2007/08
latest_season                  : 2026
unique_teams                   : 19
unique_venues                  : 60
unique_cities                  : 38
============================================================

In [9]:
import csv

file_path = next(RAW_DATA_DIR.glob("**/*_info.csv"))

print(file_path.name)

with open(file_path, encoding="utf-8") as f:
    reader = csv.reader(f)

    for row in reader:
        if row and row[0] == "info":
            print(row)

1082591_info.csv
['info', 'balls_per_over', '6']
['info', 'team', 'Sunrisers Hyderabad']
['info', 'team', 'Royal Challengers Bangalore']
['info', 'team_type', 'club']
['info', 'gender', 'male']
['info', 'season', '2017']
['info', 'date', '2017/04/05']
['info', 'event', 'Indian Premier League']
['info', 'match_id', '1082591']
['info', 'match_type', 'T20']
['info', 'overs', '20']
['info', 'match_number', '1']
['info', 'venue', 'Rajiv Gandhi International Stadium, Uppal']
['info', 'city', 'Hyderabad']
['info', 'toss_winner', 'Royal Challengers Bangalore']
['info', 'toss_decision', 'field']
['info', 'player_of_match', 'Yuvraj Singh']
['info', 'umpire', 'AY Dandekar']
['info', 'umpire', 'NJ Llong']
['info', 'reserve_umpire', 'N Pandit']
['info', 'tv_umpire', 'A Deshmukh']
['info', 'match_referee', 'J Srinath']
['info', 'target_overs', '2', '20']
['info', 'target_runs', '2', '208']
['info', 'winner', 'Sunrisers Hyderabad']
['info', 'winner_runs', '35']
['info', 'player', 'Royal Challengers Bangalore', 'CH Gayle']
['info', 'player', 'Royal Challengers Bangalore', 'Mandeep Singh']
['info', 'player', 'Royal Challengers Bangalore', 'TM Head']
['info', 'player', 'Royal Challengers Bangalore', 'KM Jadhav']
['info', 'player', 'Royal Challengers Bangalore', 'SR Watson']
['info', 'player', 'Royal Challengers Bangalore', 'Sachin Baby']
['info', 'player', 'Royal Challengers Bangalore', 'STR Binny']
['info', 'player', 'Royal Challengers Bangalore', 'S Aravind']
['info', 'player', 'Royal Challengers Bangalore', 'TS Mills']
['info', 'player', 'Royal Challengers Bangalore', 'YS Chahal']
['info', 'player', 'Royal Challengers Bangalore', 'A Choudhary']
['info', 'player', 'Sunrisers Hyderabad', 'DA Warner']
['info', 'player', 'Sunrisers Hyderabad', 'S Dhawan']
['info', 'player', 'Sunrisers Hyderabad', 'MC Henriques']
['info', 'player', 'Sunrisers Hyderabad', 'Yuvraj Singh']
['info', 'player', 'Sunrisers Hyderabad', 'DJ Hooda']
['info', 'player', 'Sunrisers Hyderabad', 'BCJ Cutting']
['info', 'player', 'Sunrisers Hyderabad', 'NV Ojha']
['info', 'player', 'Sunrisers Hyderabad', 'Bipul Sharma']
['info', 'player', 'Sunrisers Hyderabad', 'B Kumar']
['info', 'player', 'Sunrisers Hyderabad', 'A Nehra']
['info', 'player', 'Sunrisers Hyderabad', 'Rashid Khan']
['info', 'registry', 'people', 'A Choudhary', '18e6906e']
['info', 'registry', 'people', 'A Deshmukh', '6fda55cc']
['info', 'registry', 'people', 'A Nehra', '96fd40ae']
['info', 'registry', 'people', 'AY Dandekar', '2efc430e']
['info', 'registry', 'people', 'B Kumar', '2e81a32d']
['info', 'registry', 'people', 'BCJ Cutting', '2e11c706']
['info', 'registry', 'people', 'Bipul Sharma', 'c18496e1']
['info', 'registry', 'people', 'CH Gayle', 'db584dad']
['info', 'registry', 'people', 'CJ Jordan', 'ffe699c0']
['info', 'registry', 'people', 'DA Warner', 'dcce6f09']
['info', 'registry', 'people', 'DJ Hooda', '73ad96ed']
['info', 'registry', 'people', 'J Srinath', 'bad31fac']
['info', 'registry', 'people', 'KM Jadhav', '99d63244']
['info', 'registry', 'people', 'MC Henriques', '32198ae0']
['info', 'registry', 'people', 'Mandeep Singh', 'c3a96caf']
['info', 'registry', 'people', 'N Pandit', '4947c258']
['info', 'registry', 'people', 'NJ Llong', '573fb985']
['info', 'registry', 'people', 'NV Ojha', '890946a0']
['info', 'registry', 'people', 'Rashid Khan', '5f547c8b']
['info', 'registry', 'people', 'S Aravind', '957532de']
['info', 'registry', 'people', 'S Dhawan', '0a476045']
['info', 'registry', 'people', 'SR Watson', '4329fbb5']
['info', 'registry', 'people', 'STR Binny', 'bd17b45f']
['info', 'registry', 'people', 'Sachin Baby', 'dc9dd038']
['info', 'registry', 'people', 'TM Head', '12b610c2']
['info', 'registry', 'people', 'TS Mills', '245c97cb']
['info', 'registry', 'people', 'YS Chahal', '57ee1fde']
['info', 'registry', 'people', 'Yuvraj Singh', '1c914163']

In [10]:
import csv

file_path = next(CRICSHEET_DIR.glob("*_info.csv"))

print(file_path.name)

with open(file_path, encoding="utf-8") as f:
    reader = csv.reader(f)

    for row in reader:
        if row and row[0] == "info":
            print(row)

1082591_info.csv
['info', 'balls_per_over', '6']
['info', 'team', 'Sunrisers Hyderabad']
['info', 'team', 'Royal Challengers Bangalore']
['info', 'team_type', 'club']
['info', 'gender', 'male']
['info', 'season', '2017']
['info', 'date', '2017/04/05']
['info', 'event', 'Indian Premier League']
['info', 'match_id', '1082591']
['info', 'match_type', 'T20']
['info', 'overs', '20']
['info', 'match_number', '1']
['info', 'venue', 'Rajiv Gandhi International Stadium, Uppal']
['info', 'city', 'Hyderabad']
['info', 'toss_winner', 'Royal Challengers Bangalore']
['info', 'toss_decision', 'field']
['info', 'player_of_match', 'Yuvraj Singh']
['info', 'umpire', 'AY Dandekar']
['info', 'umpire', 'NJ Llong']
['info', 'reserve_umpire', 'N Pandit']
['info', 'tv_umpire', 'A Deshmukh']
['info', 'match_referee', 'J Srinath']
['info', 'target_overs', '2', '20']
['info', 'target_runs', '2', '208']
['info', 'winner', 'Sunrisers Hyderabad']
['info', 'winner_runs', '35']
['info', 'player', 'Royal Challengers Bangalore', 'CH Gayle']
['info', 'player', 'Royal Challengers Bangalore', 'Mandeep Singh']
['info', 'player', 'Royal Challengers Bangalore', 'TM Head']
['info', 'player', 'Royal Challengers Bangalore', 'KM Jadhav']
['info', 'player', 'Royal Challengers Bangalore', 'SR Watson']
['info', 'player', 'Royal Challengers Bangalore', 'Sachin Baby']
['info', 'player', 'Royal Challengers Bangalore', 'STR Binny']
['info', 'player', 'Royal Challengers Bangalore', 'S Aravind']
['info', 'player', 'Royal Challengers Bangalore', 'TS Mills']
['info', 'player', 'Royal Challengers Bangalore', 'YS Chahal']
['info', 'player', 'Royal Challengers Bangalore', 'A Choudhary']
['info', 'player', 'Sunrisers Hyderabad', 'DA Warner']
['info', 'player', 'Sunrisers Hyderabad', 'S Dhawan']
['info', 'player', 'Sunrisers Hyderabad', 'MC Henriques']
['info', 'player', 'Sunrisers Hyderabad', 'Yuvraj Singh']
['info', 'player', 'Sunrisers Hyderabad', 'DJ Hooda']
['info', 'player', 'Sunrisers Hyderabad', 'BCJ Cutting']
['info', 'player', 'Sunrisers Hyderabad', 'NV Ojha']
['info', 'player', 'Sunrisers Hyderabad', 'Bipul Sharma']
['info', 'player', 'Sunrisers Hyderabad', 'B Kumar']
['info', 'player', 'Sunrisers Hyderabad', 'A Nehra']
['info', 'player', 'Sunrisers Hyderabad', 'Rashid Khan']
['info', 'registry', 'people', 'A Choudhary', '18e6906e']
['info', 'registry', 'people', 'A Deshmukh', '6fda55cc']
['info', 'registry', 'people', 'A Nehra', '96fd40ae']
['info', 'registry', 'people', 'AY Dandekar', '2efc430e']
['info', 'registry', 'people', 'B Kumar', '2e81a32d']
['info', 'registry', 'people', 'BCJ Cutting', '2e11c706']
['info', 'registry', 'people', 'Bipul Sharma', 'c18496e1']
['info', 'registry', 'people', 'CH Gayle', 'db584dad']
['info', 'registry', 'people', 'CJ Jordan', 'ffe699c0']
['info', 'registry', 'people', 'DA Warner', 'dcce6f09']
['info', 'registry', 'people', 'DJ Hooda', '73ad96ed']
['info', 'registry', 'people', 'J Srinath', 'bad31fac']
['info', 'registry', 'people', 'KM Jadhav', '99d63244']
['info', 'registry', 'people', 'MC Henriques', '32198ae0']
['info', 'registry', 'people', 'Mandeep Singh', 'c3a96caf']
['info', 'registry', 'people', 'N Pandit', '4947c258']
['info', 'registry', 'people', 'NJ Llong', '573fb985']
['info', 'registry', 'people', 'NV Ojha', '890946a0']
['info', 'registry', 'people', 'Rashid Khan', '5f547c8b']
['info', 'registry', 'people', 'S Aravind', '957532de']
['info', 'registry', 'people', 'S Dhawan', '0a476045']
['info', 'registry', 'people', 'SR Watson', '4329fbb5']
['info', 'registry', 'people', 'STR Binny', 'bd17b45f']
['info', 'registry', 'people', 'Sachin Baby', 'dc9dd038']
['info', 'registry', 'people', 'TM Head', '12b610c2']
['info', 'registry', 'people', 'TS Mills', '245c97cb']
['info', 'registry', 'people', 'YS Chahal', '57ee1fde']
['info', 'registry', 'people', 'Yuvraj Singh', '1c914163']