# Notebook 06 – Analytics Framework

## Objective

This notebook transforms the relational IPL warehouse into reusable business analytics.

Unlike Notebook 03 (Exploratory Analysis), this notebook operates entirely on the MySQL Star Schema constructed in Notebook 05.

The notebook serves as a thin orchestration layer that delegates all business logic to reusable modules within the `src` package.

---

## Workflow

1. Validate environment
2. Load project configuration
3. Execute analytics pipeline
4. Display executive summary
5. Display domain-specific analytics
6. Export analytics artifacts
7. Display execution summary

In [1]:
from pathlib import Path

import pandas as pd

from config.config import (
    PROJECT_ROOT,
    ANALYTICS_DATA_DIR,
)

from src.workflows.analytics_pipeline import (
    run_analytics_pipeline,
)

from src.exports.analytics_exporter import (
    export_analytics_results,
)

In [2]:
print("=" * 80)
print("IPL Analytics & Strategy Platform")
print("Notebook 06 - Analytics Framework")
print("=" * 80)

print(f"Project Root : {PROJECT_ROOT}")
print(f"Analytics Dir: {ANALYTICS_DATA_DIR}")

assert Path(PROJECT_ROOT).exists(), "Project root not found."
assert Path(ANALYTICS_DATA_DIR).exists(), "Analytics directory not found."

print("\nEnvironment validation completed successfully.")

EXPORT_RESULTS = True

DISPLAY_ANALYTICS = True

================================================================================
IPL Analytics & Strategy Platform
Notebook 06 - Analytics Framework
================================================================================
Project Root : D:\IPL-Analytics-Strategy-Platform
Analytics Dir: D:\IPL-Analytics-Strategy-Platform\data\analytics

Environment validation completed successfully.

In [3]:
pipeline_results = run_analytics_pipeline()

print()

print("=" * 80)
print("Analytics Pipeline Completed")
print("=" * 80)

print(f"Status         : {pipeline_results.status}")
print(f"Execution Time : {pipeline_results.execution_time:.2f} seconds")

D:\IPL-Analytics-Strategy-Platform\src\data_access\analytics_loader.py:43: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(

================================================================================
Analytics Pipeline Completed
================================================================================
Status         : SUCCESS
Execution Time : 18.30 seconds

In [4]:
print("=" * 80)
print("EXECUTIVE SUMMARY")
print("=" * 80)

executive_summary = pipeline_results.executive_summary

summary_df = (
    pd.DataFrame(
        executive_summary.items(),
        columns=["Metric", "Value"],
    )
)

display(summary_df)

================================================================================
EXECUTIVE SUMMARY
================================================================================

                  Metric    Value
0          total_matches  1243.00
1          total_seasons    18.00
2            total_teams    17.00
3           total_venues    46.00
4           total_cities    34.00
5      completed_matches  1218.00
6      no_result_matches    25.00
7            win_by_runs   558.00
8         win_by_wickets   660.00
9  toss_field_percentage    66.37

In [5]:
print("=" * 80)
print("SEASON ANALYTICS")
print("=" * 80)

season_results = pipeline_results.analytics_results["season"]

for name, dataframe in season_results.items():

    print()

    print(name.replace("_", " ").title())

    display(dataframe)

================================================================================
SEASON ANALYTICS
================================================================================

Matches

    season  matches
0     2008       58
1     2009       57
2     2010       60
3     2011       73
4     2012       74
5     2013       76
6     2014       60
7     2015       59
8     2016       60
9     2017       59
10    2018       60
11    2019       60
12    2021      120
13    2022       74
14    2023       74
15    2024       71
16    2025       74
17    2026       74

Teams

    season  teams
0     2008      8
1     2009      8
2     2010      8
3     2011     10
4     2012      9
5     2013      9
6     2014      8
7     2015      8
8     2016      8
9     2017      8
10    2018      8
11    2019      8
12    2021      9
13    2022     10
14    2023     10
15    2024     10
16    2025     10
17    2026     10

Venues

    season  venues
0     2008       9
1     2009       8
2     2010      12
3     2011      12
4     2012      12
5     2013      13
6     2014      13
7     2015      13
8     2016      11
9     2017      10
10    2018      10
11    2019       9
12    2021       8
13    2022       6
14    2023      12
15    2024      13
16    2025      13
17    2026      13

Player Of Match

    season  unique_player_of_match_winners
0     2008                              40
1     2009                              42
2     2010                              44
3     2011                              52
4     2012                              49
5     2013                              46
6     2014                              38
7     2015                              41
8     2016                              36
9     2017                              47
10    2018                              38
11    2019                              41
12    2021                              67
13    2022                              56
14    2023                              51
15    2024                              52
16    2025                              53
17    2026                              53

Toss

    season  bat  field
0     2008   26     32
1     2009   35     22
2     2010   39     21
3     2011   25     48
4     2012   37     37
5     2013   45     31
6     2014   19     41
7     2015   25     34
8     2016   11     49
9     2017   11     48
10    2018   10     50
11    2019   10     50
12    2021   43     77
13    2022   15     59
14    2023   21     53
15    2024   19     52
16    2025   14     60
17    2026   13     61

Outcomes

    season  wins_by_runs  wins_by_wickets  no_results
0     2008            24               34           0
1     2009            27               29           1
2     2010            31               28           1
3     2011            33               39           1
4     2012            34               40           0
5     2013            37               37           2
6     2014            22               37           1
7     2015            32               24           3
8     2016            21               39           0
9     2017            26               32           1
10    2018            28               32           0
11    2019            22               35           3
12    2021            49               66           5
13    2022            37               37           0
14    2023            40               33           1
15    2024            35               36           0
16    2025            33               37           4
17    2026            27               45           2

Margins

    season  avg_runs_margin  avg_wicket_margin
0     2008            29.38               6.50
1     2009            28.30               6.21
2     2010            31.48               6.79
3     2011            33.27               6.79
4     2012            28.24               6.02
5     2013            33.54               6.14
6     2014            29.27               6.08
7     2015            26.56               6.17
8     2016            32.19               6.26
9     2017            30.31               6.38
10    2018            24.11               5.81
11    2019            30.23               5.77
12    2021            33.57               6.38
13    2022            27.95               6.00
14    2023            30.40               5.73
15    2024            30.14               5.94
16    2025            33.18               6.32
17    2026            45.59               5.78

In [6]:
print("=" * 80)
print("TEAM ANALYTICS")
print("=" * 80)

team_results = pipeline_results.analytics_results["team"]

for name, dataframe in team_results.items():

    print()

    print(name.replace("_", " ").title())

    display(dataframe)

================================================================================
TEAM ANALYTICS
================================================================================

Participation

                           team  matches
0           Chennai Super Kings      266
1               Deccan Chargers       75
2                Delhi Capitals      120
3              Delhi Daredevils      161
4                 Gujarat Lions       30
5                Gujarat Titans       77
6               Kings XI Punjab      190
7          Kochi Tuskers Kerala       14
8         Kolkata Knight Riders      278
9          Lucknow Super Giants       72
10               Mumbai Indians      291
11                Pune Warriors       46
12                 Punjab Kings       88
13             Rajasthan Royals      251
14       Rising Pune Supergiant       30
15  Royal Challengers Bengaluru      286
16          Sunrisers Hyderabad      211

Wins

                           team  wins
0           Chennai Super Kings   148
1               Deccan Chargers    29
2                Delhi Capitals    58
3              Delhi Daredevils    67
4                 Gujarat Lions    13
5                Gujarat Titans    47
6               Kings XI Punjab    85
7          Kochi Tuskers Kerala     6
8         Kolkata Knight Riders   140
9          Lucknow Super Giants    34
10               Mumbai Indians   155
11                Pune Warriors    12
12                 Punjab Kings    41
13             Rajasthan Royals   123
14       Rising Pune Supergiant    15
15  Royal Challengers Bengaluru   143
16          Sunrisers Hyderabad   102

Toss

                           team  toss_wins
0           Chennai Super Kings        133
1               Deccan Chargers         43
2                Delhi Capitals         68
3              Delhi Daredevils         80
4                 Gujarat Lions         15
5                Gujarat Titans         36
6               Kings XI Punjab         85
7          Kochi Tuskers Kerala          8
8         Kolkata Knight Riders        135
9          Lucknow Super Giants         30
10               Mumbai Indians        160
11                Pune Warriors         20
12                 Punjab Kings         44
13             Rajasthan Royals        137
14       Rising Pune Supergiant         13
15  Royal Challengers Bengaluru        136
16          Sunrisers Hyderabad        100

Season

                    team  season  matches
0    Chennai Super Kings    2008       16
1    Chennai Super Kings    2009       14
2    Chennai Super Kings    2010       16
3    Chennai Super Kings    2011       16
4    Chennai Super Kings    2012       18
..                   ...     ...      ...
154  Sunrisers Hyderabad    2022       14
155  Sunrisers Hyderabad    2023       14
156  Sunrisers Hyderabad    2024       16
157  Sunrisers Hyderabad    2025       14
158  Sunrisers Hyderabad    2026       15

[159 rows x 3 columns]

Venue

,team,venue,matches
0,Chennai Super Kings,"Arun Jaitley Stadium, Delhi",7
1,Chennai Super Kings,Barabati Stadium,1
2,Chennai Super Kings,"Barsapara Cricket Stadium, Guwahati",2
3,Chennai Super Kings,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,4
4,Chennai Super Kings,"Brabourne Stadium, Mumbai",5
...,...,...,...
428,Sunrisers Hyderabad,Shaheed Veer Narayan Singh International Stadi...,2
429,Sunrisers Hyderabad,Sharjah Cricket Stadium,7
430,Sunrisers Hyderabad,Sheikh Zayed Stadium,6
431,Sunrisers Hyderabad,"Wankhede Stadium, Mumbai",15
432,Sunrisers Hyderabad,"Zayed Cricket Stadium, Abu Dhabi",2

Margins

                           team  avg_runs_margin  avg_wicket_margin
0           Chennai Super Kings            36.29               5.97
1               Deccan Chargers            23.39               6.55
2                Delhi Capitals            24.74               5.63
3              Delhi Daredevils            27.00               6.55
4                 Gujarat Lions             1.00               5.42
5                Gujarat Titans            41.89               6.00
6               Kings XI Punjab            25.85               6.42
7          Kochi Tuskers Kerala            11.50               7.50
8         Kolkata Knight Riders            33.41               6.22
9          Lucknow Super Giants            21.48               5.31
10               Mumbai Indians            34.87               6.23
11                Pune Warriors            23.17               6.00
12                 Punjab Kings            22.12               5.58
13             Rajasthan Royals            30.64               5.92
14       Rising Pune Supergiant            25.14               6.38
15  Royal Challengers Bengaluru            33.70               6.48
16          Sunrisers Hyderabad            29.36               6.61

In [7]:
print("=" * 80)
print("VENUE ANALYTICS")
print("=" * 80)

venue_results = pipeline_results.analytics_results["venue"]

for name, dataframe in venue_results.items():

    print()

    print(name.replace("_", " ").title())

    display(dataframe)

================================================================================
VENUE ANALYTICS
================================================================================

Matches

                                                venue  matches
0                         Arun Jaitley Stadium, Delhi       44
1                                    Barabati Stadium        7
2                 Barsapara Cricket Stadium, Guwahati        8
3   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       29
4                           Brabourne Stadium, Mumbai       27
5                                        Buffalo Park        3
6                               De Beers Diamond Oval        3
7                          Dr Dy Patil Sports Academy       17
8                  Dr Dy Patil Sports Academy, Mumbai       20
9   Dr. Y.S. Rajasekhara Reddy Aca-Vdca Cricket St...       13
10  Dr. Y.S. Rajasekhara Reddy Aca-Vdca Cricket St...        4
11                Dubai International Cricket Stadium       46
12                              Eden Gardens, Kolkata      107
13                                   Feroz Shah Kotla       60
14                                         Green Park        4
15  Himachal Pradesh Cricket Association Stadium, ...       19
16                             Holkar Cricket Stadium        9
17                 Jsca International Stadium Complex        7
18                                          Kingsmead       15
19                   M Chinnaswamy Stadium, Bengaluru      104
20                             Ma Chidambaram Stadium        9
21                    Ma Chidambaram Stadium, Chepauk       48
22           Ma Chidambaram Stadium, Chepauk, Chennai       41
23  Maharaja Yadavindra Singh International Cricke...       17
24      Maharashtra Cricket Association Stadium, Pune       35
25                   Narendra Modi Stadium, Ahmedabad       41
26                                      Nehru Stadium        5
27                              New Wanderers Stadium        8
28                                           Newlands        7
29                                    Outsurance Oval        2
30       Punjab Cricket Association Is Bindra Stadium       10
31  Punjab Cricket Association Is Bindra Stadium, ...       11
32  Punjab Cricket Association Is Bindra Stadium, ...       40
33  Rajiv Gandhi International Stadium, Uppal, Hyd...       90
34                       Sardar Patel Stadium, Motera       12
35             Saurashtra Cricket Association Stadium       10
36                     Sawai Mansingh Stadium, Jaipur       68
37  Shaheed Veer Narayan Singh International Stadi...        8
38                            Sharjah Cricket Stadium       28
39                               Sheikh Zayed Stadium       29
40                                   St George'S Park        7
41                         Subrata Roy Sahara Stadium       16
42                                    Supersport Park       12
43       Vidarbha Cricket Association Stadium, Jamtha        3
44                           Wankhede Stadium, Mumbai      132
45                   Zayed Cricket Stadium, Abu Dhabi        8

Teams

                                                venue  teams
0                         Arun Jaitley Stadium, Delhi     12
1                                    Barabati Stadium      7
2                 Barsapara Cricket Stadium, Guwahati      7
3   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...     10
4                           Brabourne Stadium, Mumbai     13
5                                        Buffalo Park      5
6                               De Beers Diamond Oval      4
7                          Dr Dy Patil Sports Academy     10
8                  Dr Dy Patil Sports Academy, Mumbai     10
9   Dr. Y.S. Rajasekhara Reddy Aca-Vdca Cricket St...     10
10  Dr. Y.S. Rajasekhara Reddy Aca-Vdca Cricket St...      5
11                Dubai International Cricket Stadium     10
12                              Eden Gardens, Kolkata     17
13                                   Feroz Shah Kotla     13
14                                         Green Park      5
15  Himachal Pradesh Cricket Association Stadium, ...     11
16                             Holkar Cricket Stadium      7
17                 Jsca International Stadium Complex      6
18                                          Kingsmead      8
19                   M Chinnaswamy Stadium, Bengaluru     17
20                             Ma Chidambaram Stadium      8
21                    Ma Chidambaram Stadium, Chepauk     11
22           Ma Chidambaram Stadium, Chepauk, Chennai     10
23  Maharaja Yadavindra Singh International Cricke...     10
24      Maharashtra Cricket Association Stadium, Pune     15
25                   Narendra Modi Stadium, Ahmedabad     10
26                                      Nehru Stadium      6
27                              New Wanderers Stadium      7
28                                           Newlands      8
29                                    Outsurance Oval      3
30       Punjab Cricket Association Is Bindra Stadium      9
31  Punjab Cricket Association Is Bindra Stadium, ...      8
32  Punjab Cricket Association Is Bindra Stadium, ...     13
33  Rajiv Gandhi International Stadium, Uppal, Hyd...     16
34                       Sardar Patel Stadium, Motera      9
35             Saurashtra Cricket Association Stadium      8
36                     Sawai Mansingh Stadium, Jaipur     15
37  Shaheed Veer Narayan Singh International Stadi...      7
38                            Sharjah Cricket Stadium     10
39                               Sheikh Zayed Stadium      9
40                                   St George'S Park      8
41                         Subrata Roy Sahara Stadium      9
42                                    Supersport Park      8
43       Vidarbha Cricket Association Stadium, Jamtha      4
44                           Wankhede Stadium, Mumbai     17
45                   Zayed Cricket Stadium, Abu Dhabi      8

Season

                                venue  season  matches
0         Arun Jaitley Stadium, Delhi    2018       14
1         Arun Jaitley Stadium, Delhi    2019       14
2         Arun Jaitley Stadium, Delhi    2021        8
3         Arun Jaitley Stadium, Delhi    2023       14
4         Arun Jaitley Stadium, Delhi    2024       10
..                                ...     ...      ...
192          Wankhede Stadium, Mumbai    2023       14
193          Wankhede Stadium, Mumbai    2024       14
194          Wankhede Stadium, Mumbai    2025       14
195          Wankhede Stadium, Mumbai    2026       14
196  Zayed Cricket Stadium, Abu Dhabi    2021       16

[197 rows x 3 columns]

Toss

                                                venue  bat  field
0                         Arun Jaitley Stadium, Delhi   13     31
1                                    Barabati Stadium    2      5
2                 Barsapara Cricket Stadium, Guwahati    1      7
3   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...    6     23
4                           Brabourne Stadium, Mumbai    9     18
5                                        Buffalo Park    3      0
6                               De Beers Diamond Oval    2      1
7                          Dr Dy Patil Sports Academy    7     10
8                  Dr Dy Patil Sports Academy, Mumbai    3     17
9   Dr. Y.S. Rajasekhara Reddy Aca-Vdca Cricket St...    5      8
10  Dr. Y.S. Rajasekhara Reddy Aca-Vdca Cricket St...    3      1
11                Dubai International Cricket Stadium   19     27
12                              Eden Gardens, Kolkata   35     72
13                                   Feroz Shah Kotla   26     34
14                                         Green Park    0      4
15  Himachal Pradesh Cricket Association Stadium, ...    2     17
16                             Holkar Cricket Stadium    1      8
17                 Jsca International Stadium Complex    3      4
18                                          Kingsmead   10      5
19                   M Chinnaswamy Stadium, Bengaluru    9     95
20                             Ma Chidambaram Stadium    2      7
21                    Ma Chidambaram Stadium, Chepauk   34     14
22           Ma Chidambaram Stadium, Chepauk, Chennai   15     26
23  Maharaja Yadavindra Singh International Cricke...    5     12
24      Maharashtra Cricket Association Stadium, Pune    4     31
25                   Narendra Modi Stadium, Ahmedabad    8     33
26                                      Nehru Stadium    2      3
27                              New Wanderers Stadium    2      6
28                                           Newlands    4      3
29                                    Outsurance Oval    1      1
30       Punjab Cricket Association Is Bindra Stadium    1      9
31  Punjab Cricket Association Is Bindra Stadium, ...    2      9
32  Punjab Cricket Association Is Bindra Stadium, ...   14     26
33  Rajiv Gandhi International Stadium, Uppal, Hyd...   38     52
34                       Sardar Patel Stadium, Motera    6      6
35             Saurashtra Cricket Association Stadium    3      7
36                     Sawai Mansingh Stadium, Jaipur   28     40
37  Shaheed Veer Narayan Singh International Stadi...    3      5
38                            Sharjah Cricket Stadium    8     20
39                               Sheikh Zayed Stadium   15     14
40                                   St George'S Park    7      0
41                         Subrata Roy Sahara Stadium   15      1
42                                    Supersport Park    6      6
43       Vidarbha Cricket Association Stadium, Jamtha    2      1
44                           Wankhede Stadium, Mumbai   31    101
45                   Zayed Cricket Stadium, Abu Dhabi    3      5

Margins

,venue,avg_runs_margin,avg_wicket_margin
0,"Arun Jaitley Stadium, Delhi",29.65,6.36
1,Barabati Stadium,18.25,6.67
2,"Barsapara Cricket Stadium, Guwahati",23.75,6.75
3,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,30.45,6.12
4,"Brabourne Stadium, Mumbai",25.93,6.31
5,Buffalo Park,43.50,7.00
6,De Beers Diamond Oval,53.00,5.00
7,Dr Dy Patil Sports Academy,28.14,6.40
8,"Dr Dy Patil Sports Academy, Mumbai",28.30,6.10
9,Dr. Y.S. Rajasekhara Reddy Aca-Vdca Cricket St...,40.29,5.00
10,Dr. Y.S. Rajasekhara Reddy Aca-Vdca Cricket St...,63.00,4.00
11,Dubai International Cricket Stadium,35.19,6.32
12,"Eden Gardens, Kolkata",28.09,6.00
13,Feroz Shah Kotla,31.29,6.19
14,Green Park,NaN,5.50
15,"Himachal Pradesh Cricket Association Stadium, ...",48.55,5.14
16,Holkar Cricket Stadium,31.00,7.25
17,Jsca International Stadium Complex,20.50,4.80
18,Kingsmead,17.67,5.50
19,"M Chinnaswamy Stadium, Bengaluru",35.82,6.02
20,Ma Chidambaram Stadium,39.00,6.20
21,"Ma Chidambaram Stadium, Chepauk",23.83,6.53
22,"Ma Chidambaram Stadium, Chepauk, Chennai",30.71,6.09
23,Maharaja Yadavindra Singh International Cricke...,27.00,5.22
24,"Maharashtra Cricket Association Stadium, Pune",39.39,5.76
25,"Narendra Modi Stadium, Ahmedabad",41.45,5.52
26,Nehru Stadium,36.67,6.50
27,New Wanderers Stadium,8.33,7.00
28,Newlands,36.25,9.00
29,Outsurance Oval,14.00,6.00
30,Punjab Cricket Association Is Bindra Stadium,11.25,6.83
31,"Punjab Cricket Association Is Bindra Stadium, ...",15.00,6.67
32,"Punjab Cricket Association Is Bindra Stadium, ...",32.67,6.32
33,"Rajiv Gandhi International Stadium, Uppal, Hyd...",28.34,6.55
34,"Sardar Patel Stadium, Motera",30.00,7.60
35,Saurashtra Cricket Association Stadium,23.33,8.00
36,"Sawai Mansingh Stadium, Jaipur",38.12,6.41
37,Shaheed Veer Narayan Singh International Stadi...,10.50,5.50
38,Sharjah Cricket Stadium,36.70,6.11
39,Sheikh Zayed Stadium,37.64,6.56
40,St George'S Park,66.67,5.50
41,Subrata Roy Sahara Stadium,26.60,7.00
42,Supersport Park,20.25,6.12
43,"Vidarbha Cricket Association Stadium, Jamtha",7.50,6.00
44,"Wankhede Stadium, Mumbai",27.73,5.94
45,"Zayed Cricket Stadium, Abu Dhabi",26.33,6.20

In [8]:
print("=" * 80)
print("PLAYER ANALYTICS")
print("=" * 80)

player_results = pipeline_results.analytics_results["player"]

for name, dataframe in player_results.items():

    print()

    print(name.replace("_", " ").title())

    display(dataframe)

================================================================================
PLAYER ANALYTICS
================================================================================

Awards

           player  awards
0      A Chandila       1
1        A Kumble       3
2       A Manohar       1
3        A Mishra      12
4         A Nehra       6
..            ...     ...
316     YK Pathan      16
317     YS Chahal       7
318   Yash Thakur       1
319  Yuvraj Singh       5
320        Z Khan       1

[321 rows x 2 columns]

Season

     season         player  awards
0      2008       A Kumble       1
1      2008       A Mishra       1
2      2008        A Nehra       1
3      2008   AC Gilchrist       2
4      2008    BB McCullum       1
..      ...            ...     ...
841    2026    Tilak Varma       2
842    2026        V Kohli       3
843    2026  V Suryavanshi       3
844    2026        VR Iyer       1
845    2026    YBK Jaiswal       1

[846 rows x 3 columns]

Team

                    team         player  awards
0    Chennai Super Kings        A Nehra       3
1    Chennai Super Kings      AM Rahane       1
2    Chennai Super Kings      AT Rayudu       3
3    Chennai Super Kings    BB McCullum       2
4    Chennai Super Kings  BW Hilfenhaus       2
..                   ...            ...     ...
511  Sunrisers Hyderabad       TA Boult       1
512  Sunrisers Hyderabad        TM Head       3
513  Sunrisers Hyderabad    Umran Malik       1
514  Sunrisers Hyderabad        WP Saha       1
515  Sunrisers Hyderabad   Yuvraj Singh       1

[516 rows x 3 columns]

Venue

                                venue           player  awards
0         Arun Jaitley Stadium, Delhi         A Mishra       2
1         Arun Jaitley Stadium, Delhi   AB de Villiers       1
2         Arun Jaitley Stadium, Delhi       AS Rajpoot       1
3         Arun Jaitley Stadium, Delhi    Akash Madhwal       1
4         Arun Jaitley Stadium, Delhi  B Sai Sudharsan       2
..                                ...              ...     ...
950  Zayed Cricket Stadium, Abu Dhabi    KS Williamson       1
951  Zayed Cricket Stadium, Abu Dhabi        RA Jadeja       1
952  Zayed Cricket Stadium, Abu Dhabi       RD Gaikwad       1
953  Zayed Cricket Stadium, Abu Dhabi        SP Narine       1
954  Zayed Cricket Stadium, Abu Dhabi          SS Iyer       1

[955 rows x 3 columns]

Match Type

    match_type        player  awards
0          T20    A Chandila       1
1          T20      A Kumble       3
2          T20     A Manohar       1
3          T20      A Mishra      12
4          T20       A Nehra       6
..         ...           ...     ...
316        T20     YK Pathan      16
317        T20     YS Chahal       7
318        T20   Yash Thakur       1
319        T20  Yuvraj Singh       5
320        T20        Z Khan       1

[321 rows x 3 columns]

In [9]:
print("=" * 80)
print("MATCH ANALYTICS")
print("=" * 80)

match_results = pipeline_results.analytics_results["match"]

for name, dataframe in match_results.items():

    print()

    print(name.replace("_", " ").title())

    display(dataframe)

================================================================================
MATCH ANALYTICS
================================================================================

Match Types

  match_type  matches  percentage
0        T20     1243       100.0

Results

            metric  value
0     wins_by_runs    558
1  wins_by_wickets    660
2       no_results     25

Toss

  toss_decision  matches
0         field      825
1           bat      418

Toss Advantage

     toss_advantage  matches  percentage
0     Won Toss Only      615       49.48
1  Won Toss & Match      628       50.52

Margins

               metric  runs_margin  wickets_margin
0                mean        31.04            6.17
1              median        23.00            6.00
2             minimum         1.00            1.00
3             maximum       146.00           10.00
4  standard_deviation        27.16            1.83

In [10]:
print("=" * 80)
print("HEAD-TO-HEAD ANALYTICS")
print("=" * 80)

head_to_head_results = pipeline_results.analytics_results["head_to_head"]

for name, dataframe in head_to_head_results.items():

    print()

    print(name.replace("_", " ").title())

    display(dataframe)

================================================================================
HEAD-TO-HEAD ANALYTICS
================================================================================

Matches

                         team_a                       team_b  matches
0           Chennai Super Kings              Deccan Chargers       10
1           Chennai Super Kings               Delhi Capitals       15
2           Chennai Super Kings             Delhi Daredevils       18
3           Chennai Super Kings               Gujarat Titans       10
4           Chennai Super Kings              Kings XI Punjab       23
..                          ...                          ...      ...
92             Rajasthan Royals  Royal Challengers Bengaluru       34
93             Rajasthan Royals          Sunrisers Hyderabad       24
94       Rising Pune Supergiant  Royal Challengers Bengaluru        4
95       Rising Pune Supergiant          Sunrisers Hyderabad        4
96  Royal Challengers Bengaluru          Sunrisers Hyderabad       27

[97 rows x 3 columns]

Wins

,team_a,team_b,team,wins
0,Chennai Super Kings,Deccan Chargers,Chennai Super Kings,6
1,Chennai Super Kings,Deccan Chargers,Deccan Chargers,4
2,Chennai Super Kings,Delhi Capitals,Chennai Super Kings,9
3,Chennai Super Kings,Delhi Capitals,Delhi Capitals,6
4,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,12
...,...,...,...,...
180,Rising Pune Supergiant,Royal Challengers Bengaluru,Royal Challengers Bengaluru,2
181,Rising Pune Supergiant,Sunrisers Hyderabad,Rising Pune Supergiant,3
182,Rising Pune Supergiant,Sunrisers Hyderabad,Sunrisers Hyderabad,1
183,Royal Challengers Bengaluru,Sunrisers Hyderabad,Royal Challengers Bengaluru,12
184,Royal Challengers Bengaluru,Sunrisers Hyderabad,Sunrisers Hyderabad,14

Season

                          team_a               team_b  season  matches
0            Chennai Super Kings      Deccan Chargers    2008        2
1            Chennai Super Kings      Deccan Chargers    2009        2
2            Chennai Super Kings      Deccan Chargers    2010        3
3            Chennai Super Kings      Deccan Chargers    2011        1
4            Chennai Super Kings      Deccan Chargers    2012        2
..                           ...                  ...     ...      ...
623  Royal Challengers Bengaluru  Sunrisers Hyderabad    2022        2
624  Royal Challengers Bengaluru  Sunrisers Hyderabad    2023        1
625  Royal Challengers Bengaluru  Sunrisers Hyderabad    2024        2
626  Royal Challengers Bengaluru  Sunrisers Hyderabad    2025        1
627  Royal Challengers Bengaluru  Sunrisers Hyderabad    2026        2

[628 rows x 4 columns]

Venue

,team_a,team_b,venue,matches
0,Chennai Super Kings,Deccan Chargers,Buffalo Park,1
1,Chennai Super Kings,Deccan Chargers,Dr Dy Patil Sports Academy,1
2,Chennai Super Kings,Deccan Chargers,Dr. Y.S. Rajasekhara Reddy Aca-Vdca Cricket St...,1
3,Chennai Super Kings,Deccan Chargers,Kingsmead,1
4,Chennai Super Kings,Deccan Chargers,"Ma Chidambaram Stadium, Chepauk",4
...,...,...,...,...
579,Royal Challengers Bengaluru,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal, Hyd...",10
580,Royal Challengers Bengaluru,Sunrisers Hyderabad,Sharjah Cricket Stadium,1
581,Royal Challengers Bengaluru,Sunrisers Hyderabad,Sheikh Zayed Stadium,1
582,Royal Challengers Bengaluru,Sunrisers Hyderabad,"Wankhede Stadium, Mumbai",1
583,Royal Challengers Bengaluru,Sunrisers Hyderabad,"Zayed Cricket Stadium, Abu Dhabi",1

Margins

,team_a,team_b,avg_runs_margin,avg_wicket_margin
0,Chennai Super Kings,Deccan Chargers,41.67,6.50
1,Chennai Super Kings,Delhi Capitals,48.38,5.57
2,Chennai Super Kings,Delhi Daredevils,39.10,6.75
3,Chennai Super Kings,Gujarat Titans,57.00,5.60
4,Chennai Super Kings,Kings XI Punjab,27.27,7.27
...,...,...,...,...
92,Rajasthan Royals,Royal Challengers Bengaluru,47.64,6.86
93,Rajasthan Royals,Sunrisers Hyderabad,37.17,6.00
94,Rising Pune Supergiant,Royal Challengers Bengaluru,33.67,7.00
95,Rising Pune Supergiant,Sunrisers Hyderabad,16.67,6.00
96,Royal Challengers Bengaluru,Sunrisers Hyderabad,32.27,6.36

In [11]:
if EXPORT_RESULTS:

    export_analytics_results(
        pipeline_results=pipeline_results,
    )

    print()

    print("=" * 80)
    print("Analytics artifacts exported successfully.")
    print("=" * 80)

================================================================================
Analytics artifacts exported successfully.
================================================================================

In [12]:
print("=" * 80)
print("PIPELINE EXECUTION SUMMARY")
print("=" * 80)

print(f"Status          : {pipeline_results.status}")
print(f"Execution Time  : {pipeline_results.execution_time:.2f} seconds")

print()
print("Notebook 06 completed successfully.")

================================================================================
PIPELINE EXECUTION SUMMARY
================================================================================
Status          : SUCCESS
Execution Time  : 18.30 seconds

Notebook 06 completed successfully.